@url_dev=http://localhost:3052/v1/api

### sign up
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: abcasdasasasdasdasd

{
  "name": "Shop TIPS",
  "email": "shoptipjs04@gmail.com",
  "password": "abc123"
}